services:
  mariadb:
    container_name: mariadb
    image: mariadb
    build: ./requirements/mariadb
    env_file: .env
    networks:
      - inception
    expose:
      - "3306"
    volumes:
      - db:/var/lib/mysql
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${SQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    expose:
      - "9000"
    volumes:
      - wp:/var/www/rel-fila/wordpress
    env_file: .env
    restart: always
  
  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx
    networks:
      - inception
    depends_on:
      - wordpress
      - phpmyadmin
    ports:
      - "443:443"
    volumes:
      - wp:/var/www/rel-fila/wordpress
    env_file: .env
    restart: always

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    networks:
      - inception
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      PMA_HOST: mariadb
      PMA_USER: ${SQL_USER}
      PMA_PASSWORD: ${SQL_PASSWORD}
      PMA_ARBITRARY: 1
    restart: always
    expose:
      - "5000"

networks:
  inception:
    driver: bridge

volumes:
  wp:
    driver: local
    name: wp
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/wordpress'

  db:
    driver: local
    name: db
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '${HOME}/data/mariadb'
