- hosts: digital_ocean
  tasks:
    - apt:
        name: 
          - docker.io
          - docker-compose
          - make
        state: present
        update_cache: yes

    - name: Copy srcs directory
      copy:
        src: srcs/
        dest: /root/srcs/
        owner: root
        group: root
        mode: 0755
  
    - name: Copy .env into srcs folder
      copy:
        src: .env
        dest: /root/srcs/.env
        owner: root
        group: root
        mode: 0644


    - name: Update DOMAIN_NAME in .env to match server IP
      replace:
        path: /root/srcs/.env
        regexp: '^DOMAIN_NAME=.*$'
        replace: "DOMAIN_NAME=https://{{ ansible_host }}"

    - name: Run make in srcs folder
      command: make
      args:
        chdir: /root/srcs/
